[package]
name = "rustcaptcha"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "rustcaptcha"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.32.1"
captcha = "0.0.9"
base64 = "0.22.0"
